# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kb_index_service_pb2 as kb__index__service__pb2


class KBIndexServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/KBIndexService/Create',
                request_serializer=kb__index__service__pb2.KBIndexRequest.SerializeToString,
                response_deserializer=kb__index__service__pb2.KBIndexReply.FromString,
                )
        self.Modify = channel.unary_unary(
                '/KBIndexService/Modify',
                request_serializer=kb__index__service__pb2.KBIndexRequest.SerializeToString,
                response_deserializer=kb__index__service__pb2.KBIndexReply.FromString,
                )
        self.Delete = channel.unary_unary(
                '/KBIndexService/Delete',
                request_serializer=kb__index__service__pb2.KBIndexRequest.SerializeToString,
                response_deserializer=kb__index__service__pb2.KBIndexReply.FromString,
                )


class KBIndexServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Modify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KBIndexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=kb__index__service__pb2.KBIndexRequest.FromString,
                    response_serializer=kb__index__service__pb2.KBIndexReply.SerializeToString,
            ),
            'Modify': grpc.unary_unary_rpc_method_handler(
                    servicer.Modify,
                    request_deserializer=kb__index__service__pb2.KBIndexRequest.FromString,
                    response_serializer=kb__index__service__pb2.KBIndexReply.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kb__index__service__pb2.KBIndexRequest.FromString,
                    response_serializer=kb__index__service__pb2.KBIndexReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KBIndexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KBIndexService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KBIndexService/Create',
            kb__index__service__pb2.KBIndexRequest.SerializeToString,
            kb__index__service__pb2.KBIndexReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Modify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KBIndexService/Modify',
            kb__index__service__pb2.KBIndexRequest.SerializeToString,
            kb__index__service__pb2.KBIndexReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KBIndexService/Delete',
            kb__index__service__pb2.KBIndexRequest.SerializeToString,
            kb__index__service__pb2.KBIndexReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
